spring:
  datasource:
    url: jdbc:postgresql://localhost/lakeside
    username: gunthermasihaas
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLInnoDBDialect
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_identifiers: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      file-size-threshold: 2KB
  mvc:
    throw-exception-if-no-handler-found: true
    async:
      request-timeout: 3600000
